include:
  - remote: 'https://gitlab.com/cscs-ci/recipes/-/raw/master/templates/v2/.ci-ext.yml'

stages:
  - deps
  - build
  - test

.deps_common:
  extends: .container-builder
  stage: deps
  timeout: 6 hours
  before_script:
    - echo $DOCKERHUB_TOKEN | podman login docker.io -u $DOCKERHUB_USERNAME --password-stdin
    - TAG_IMAGE=`echo ${BASE_IMAGE##*/} | sed 's/[:]//g'`
    - TAG_APTGET=`echo ${EXTRA_APTGET} | sha256sum - | head -c 6`
    - TAG_COMPILER=`echo ${COMPILER}_CXX${CXXSTD} | sed 's/[@]//g'`
    - TAG_DOCKERFILE=`sha256sum $DOCKERFILE | head -c 16`
    - TAG_SPACK=`echo $SPACK_SHA | tail -c 11`
    - TAG_SPACK_BUILDCACHE=`echo $SPACK_BUILDCACHE | tail -c 11`
    - TAG_REPO=`find $SPACK_DLAF_FORTRAN_REPO -type f -exec sha256sum {} \; | sha256sum - | head -c 16`
    - TAG_ENVIRONMENT=`cat $SPACK_ENVIRONMENT $COMMON_SPACK_ENVIRONMENT | sha256sum | head -c 16`
    - TAG=${TAG_IMAGE}-${TAG_APTGET}-${TAG_COMPILER}-MKL${USE_MKL}-${TAG_DOCKERFILE}-${TAG_SPACK}-${TAG_SPACK_BUILDCACHE}-${TAG_REPO}-${TAG_ENVIRONMENT}
    - export PERSIST_IMAGE_NAME=$BUILD_IMAGE:$TAG
    - echo "BUILD_IMAGE=$PERSIST_IMAGE_NAME" > build.env
    - echo "USE_MKL=$USE_MKL" >> build.env
    - 'echo "INFO: Building image $PERSIST_IMAGE_NAME"'
    - 'echo "INFO: Using NUM_CORES_BUILD_DEPS=$NUM_CORES_BUILD_DEPS"'
  artifacts:
    reports:
      dotenv: build.env
  variables:
    SPACK_SHA: develop-2025-02-02
    SPACK_BUILDCACHE: develop-2025-02-02
    SPACK_DLAF_FORTRAN_REPO: ./spack
    DOCKER_BUILD_ARGS: '[
        "BASE_IMAGE",
        "BUILDKIT_INLINE_CACHE=1",
        "SPACK_SHA",
        "SPACK_BUILDCACHE",
        "EXTRA_APTGET",
        "COMPILER",
        "SPACK_ENVIRONMENT",
        "COMMON_SPACK_ENVIRONMENT",
        "SPACK_DLAF_FORTRAN_REPO",
        "NUM_PROCS=$NUM_CORES_BUILD_DEPS"
      ]'
    DOCKERFILE: ci/docker/build.Dockerfile
    BASE_IMAGE: docker.io/ubuntu:22.04
    EXTRA_APTGET: ""
    USE_MKL: "OFF"
    COMMON_SPACK_ENVIRONMENT: ci/docker/common.yaml

.build_common:
  extends: .container-builder
  stage: build
  timeout: 1 hours
  before_script:
    - 'echo $DOCKERHUB_TOKEN | podman login docker.io -u $DOCKERHUB_USERNAME --password-stdin'
    - 'echo "INFO: Using NUM_CORES_BUILD_DLAF_FORTRAN=$NUM_CORES_BUILD_DLAF_FORTRAN"'
  after_script:
    - podman run -v $PWD/ci/ctest_to_gitlab.sh:/ctest_to_gitlab.sh $DEPLOY_IMAGE /ctest_to_gitlab.sh "$DEPLOY_IMAGE" "$THREADS_MAX_PER_TASK" "$THREADS_PER_NODE" "$SLURM_CONSTRAINT" "$RUNNER" > pipeline.yml
  variables:
    PERSIST_IMAGE_NAME: $DEPLOY_IMAGE
    DOCKER_BUILD_ARGS: '[
        "BUILD_IMAGE",
        "DEPLOY_BASE_IMAGE",
        "EXTRA_APTGET_DEPLOY",
        "USE_MKL",
        "NUM_PROCS=$NUM_CORES_BUILD_DLAF_FORTRAN"
      ]'
    DOCKERFILE: ci/docker/deploy.Dockerfile
    DEPLOY_BASE_IMAGE: docker.io/ubuntu:22.04
    EXTRA_APTGET_DEPLOY: ""
  artifacts:
    paths:
      - pipeline.yml

.build_for_eiger:
  variables:
    RUNNER: ".container-runner-eiger"
    SLURM_CONSTRAINT: mc
    THREADS_MAX_PER_TASK: 32
    THREADS_PER_NODE: 256

.run_common:
  stage: test
  trigger:
    strategy: depend
    forward:
      pipeline_variables: true
