name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: |
          python -m pip install --upgrade pip
          python -m pip install ford
      - name: Build
        run: |
          python -m ford --output_dir doc-ford DLA-Future-Fortran.md
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: doc-ford
          committer: Rocco Meli <rocco.meli@cscs.ch>
          author: Rocco Meli <rocco.meli@cscs.ch>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
